runner:
    optim: AdamW_finetune
    train_batch_size: 128
    valid_batch_size: 128
    shuffle: False
    multi_gpu: True
    device: cuda
    total_steps: 2000 
    lr: 5e-4
    num_workers: 16
    log_step: 100
    checkpoint_step: 100
    grad_clip: 1.0
    output_tb: True
    #start_from_ckpt: /storage/czw/self_supervised_seeg/outputs/2022-05-13/02-28-15/checkpoint_last.pth
    results_dir: ???
    scheduler:
        #name: reduce_on_plateau
        name: ramp_up
        warmup: 0.025
        gamma: 0.95
        total_steps: ${exp.runner.total_steps}
