name: Update Leaderboard

on:
  push:
    branches:
      - main
    paths:
      - "evaluation/**"  # Only run when evaluation files change

permissions:
  contents: write

jobs:
  update-leaderboard:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout btbench repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install --upgrade pip

      - name: Run update_leaderboard.py
        run: python update_leaderboard.py

      - name: Commit and Push Changes in btbench
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git add leaderboard/public/leaderboard_data.json
          git commit -m "Automated update of leaderboard data"
          git push

      - name: Push updated JSON to leaderboard repo
        env:
          LEADERBOARD_PAT: ${{ secrets.LEADERBOARD_PAT }}
        run: |
          git clone https://x-access-token:${{ secrets.LEADERBOARD_PAT }}@github.com/azaho/leaderboard.git
          cp leaderboard/public/leaderboard_data.json leaderboard/
          cd leaderboard
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git add leaderboard_data.json
          git commit -m "Automated leaderboard update from btbench"
          git push origin main

