name: Update Leaderboard

on:
  push:
    paths:
      - 'evaluation/**'  # Runs when any file in evaluation/ changes
  workflow_dispatch:  # Allows manual triggering from GitHub Actions UI

jobs:
  update-leaderboard:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout btbench repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install pyyaml

      - name: Checkout leaderboard repository
        run: |
          git clone https://oauth2:${{ secrets.LEADERBOARD_PAT 
}}@github.com/azaho/leaderboard.git
          cd leaderboard
          git config user.name "github-actions[bot]"
          git config user.email "github-actions@github.com"

      - name: Update Leaderboard Data
        run: python update_leaderboard.py

      - name: Commit and Push changes
        run: |
          cd leaderboard
          git add public/leaderboard_data.json
          git commit -m "Update leaderboard with new submissions"
          git push origin main

